server:
  port: 8080
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/booklibrary?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
 #    relay: /topic
#

jwt:
  signerKey: "4GTzbXf7UmaZduTlbkG/gm4zSP9N9T8KR9X7iUf8TXTHuTG4ByLb7skybWCngRGx"
  valid-duration: 86400 #in second
  refreshable-duration: 360000 #in second


